# CercleCi version
version: 2.1
description: |
    "Build, test  python packages |
    deploy to DockerHub and deploy to Heroku"

orbs:
  python: circleci/python@1.4.0
  heroku: circleci/heroku@1.2.6


jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - run:
          command: pytest
          name: run pytest
      - run:
          command: flake8
          name: run flake8

workflows:
  master:
    jobs:
      - build-and-test
