# CercleCi version
version: 2.1
description: |
    "Build, test  python packages |
    deploy to DockerHub and deploy to Heroku"

orbs:
  python: circleci/python@1.4.0
  docker: circleci/docker@1.6.0
  heroku: circleci/heroku@1.2.6


jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - run:
          command: pytest
          name: run pytest
      - run:
          command: flake8
          name: run flake8
  deploy_heroku:
    executor: heroku/default
    steps:
      - checkout
      # Install the Heroku CLI only if not already installed in the system.
      - heroku/install
      - run:
          command: >
            echo "Please wait for deployment."
      # - run: heroku config:set DSN_SENTRY=$DSN_SENTRY -a $HEROKU_APP_NAME
      - heroku/deploy-via-git:
          app-name: $HEROKU_APP_NAME
          api-key: HEROKU_API_KEY
          environment:
            DSN_SENTRY: $DSN_SENTRY


workflows:
  master:
    jobs:
      - build-and-test
      
      - docker/publish:
          requires:
            - build-and-test
          image: $DOCKER_LOGIN/$PROJECT_REPONAME
          tag: $CIRCLE_SHA1
          # Publish to dockerhub only if branch master
          filters:
            branches:
              only: master
      - deploy_heroku:
          requires:
            - docker/publish
          filters:
            branches:
              only: master
